-- Iberail · actividad en la web (pestaña «En directo» del panel)
-- Ejecutar UNA vez en Supabase → SQL Editor.
--
-- · visitas:   una fila por página vista, SIN identificar a nadie (ni IP, ni cookies, ni id de visitante).
-- · actividad: lo que hace cada cliente CON CUENTA dentro de la web (páginas, alojamientos, pagos, avisos…).
-- Solo el equipo puede leerlas. Se borran solas a los 90 días.

create extension if not exists pg_cron;

create table if not exists public.visitas (
  id         bigint generated by default as identity primary key,
  pagina     text not null check (char_length(pagina) <= 80),
  con_cuenta boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists visitas_fecha_idx on public.visitas (created_at desc);

create table if not exists public.actividad (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  tipo       text not null check (char_length(tipo) <= 40),
  pagina     text check (char_length(pagina) <= 80),
  detalle    jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists actividad_fecha_idx on public.actividad (created_at desc);
create index if not exists actividad_user_idx on public.actividad (user_id, created_at desc);

alter table public.visitas enable row level security;
alter table public.actividad enable row level security;

-- cualquiera puede apuntar una visita (sin datos personales); solo el equipo las lee
drop policy if exists "visitas: apuntar" on public.visitas;
create policy "visitas: apuntar" on public.visitas for insert to anon, authenticated with check (true);
drop policy if exists "visitas: equipo" on public.visitas;
create policy "visitas: equipo" on public.visitas for select to authenticated using (public.is_admin());

-- cada cliente solo puede apuntar su propia actividad; solo el equipo la lee
drop policy if exists "actividad: apuntar la mía" on public.actividad;
create policy "actividad: apuntar la mía" on public.actividad for insert to authenticated
  with check (user_id = auth.uid() and char_length(detalle::text) <= 2000);
drop policy if exists "actividad: equipo" on public.actividad;
create policy "actividad: equipo" on public.actividad for select to authenticated using (public.is_admin());

-- que el panel vea la actividad al momento
do $$ begin
  alter publication supabase_realtime add table public.actividad;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.visitas;
exception when duplicate_object then null; end $$;

-- limpieza diaria: se borra todo lo que tenga más de 90 días
select cron.unschedule('iberail-limpiar-actividad') where exists (select 1 from cron.job where jobname = 'iberail-limpiar-actividad');
select cron.schedule('iberail-limpiar-actividad', '30 3 * * *', $$
  delete from public.visitas   where created_at < now() - interval '90 days';
  delete from public.actividad where created_at < now() - interval '90 days';
$$);
