-- Iberail · alojamientos del grupo (fichas por ciudad con fotos)
-- Ejecutar UNA vez en Supabase → SQL Editor.

create table if not exists public.alojamientos (
  id         bigint generated by default as identity primary key,
  grupo_id   bigint not null references public.grupos(id) on delete cascade,
  ciudad     text not null,
  nombre     text,
  enlace     text,              -- anuncio de Airbnb / Booking
  direccion  text,
  entrada    date,
  salida     date,
  notas      text,
  fotos      jsonb not null default '[]'::jsonb,   -- rutas dentro del bucket «alojamientos», en orden (la 1.ª es la portada)
  created_at timestamptz not null default now()
);
create index if not exists alojamientos_grupo_idx on public.alojamientos (grupo_id, entrada);

-- quién ve qué: los miembros del grupo lo ven; el equipo lo ve y lo edita todo
alter table public.alojamientos enable row level security;
drop policy if exists "alojamientos: ver" on public.alojamientos;
create policy "alojamientos: ver" on public.alojamientos for select to authenticated
  using (public.is_admin() or exists (select 1 from public.grupo_miembros m where m.grupo_id = alojamientos.grupo_id and m.user_id = auth.uid()));
drop policy if exists "alojamientos: equipo" on public.alojamientos;
create policy "alojamientos: equipo" on public.alojamientos for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- fotos: carpeta privada «alojamientos/<id del grupo>/…»
insert into storage.buckets (id, name, public) values ('alojamientos', 'alojamientos', false)
  on conflict (id) do nothing;
drop policy if exists "alojamientos fotos: ver" on storage.objects;
create policy "alojamientos fotos: ver" on storage.objects for select to authenticated
  using (bucket_id = 'alojamientos' and (public.is_admin() or exists (
    select 1 from public.grupo_miembros m where m.grupo_id::text = (storage.foldername(name))[1] and m.user_id = auth.uid())));
drop policy if exists "alojamientos fotos: subir" on storage.objects;
create policy "alojamientos fotos: subir" on storage.objects for insert to authenticated
  with check (bucket_id = 'alojamientos' and public.is_admin());
drop policy if exists "alojamientos fotos: borrar" on storage.objects;
create policy "alojamientos fotos: borrar" on storage.objects for delete to authenticated
  using (bucket_id = 'alojamientos' and public.is_admin());

-- que el grupo vea los cambios al momento (sin recargar)
do $$ begin
  alter publication supabase_realtime add table public.alojamientos;
exception when duplicate_object then null; end $$;
