-- Iberail · contratos de viaje firmados en la web
-- Ejecutar UNA vez en Supabase → SQL Editor.
--
-- El equipo envía el contrato a cada viajero del grupo (tipo «adulto» o «menor») desde el panel.
-- El viajero (o, si es menor, su padre/madre/tutor) lo lee y lo firma en «Mis grupos».
-- Una vez firmado ya no se puede cambiar: queda guardado con la fecha, los datos y la firma.

create table if not exists public.contratos (
  id           bigint generated by default as identity primary key,
  grupo_id     bigint not null references public.grupos(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  tipo         text not null check (tipo in ('adulto', 'menor')),
  estado       text not null default 'pendiente' check (estado in ('pendiente', 'firmado', 'anulado')),
  condiciones  jsonb not null default '{}'::jsonb,   -- lo que fija el equipo al enviarlo: calendario de pagos, gastos de cancelación…
  contenido    jsonb,                                -- foto del contrato en el momento de firmar (precio, ruta, alojamientos, texto)
  datos        jsonb,                                -- datos que rellena quien firma (viajero y, si es menor, tutor)
  firma        text,                                 -- firma del viajero o del tutor (imagen PNG en base64)
  firma_menor  text,                                 -- firma del menor (opcional)
  enviado_at   timestamptz not null default now(),
  firmado_at   timestamptz,
  firmado_ua   text
);
create unique index if not exists contratos_vigente_idx on public.contratos (grupo_id, user_id) where estado <> 'anulado';

alter table public.contratos enable row level security;
drop policy if exists "contratos: ver el mío" on public.contratos;
create policy "contratos: ver el mío" on public.contratos for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
drop policy if exists "contratos: equipo" on public.contratos;
create policy "contratos: equipo" on public.contratos for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- firmar: solo el propio viajero, solo si está pendiente, y una sola vez
create or replace function public.firmar_contrato(p_id bigint, p_datos jsonb, p_firma text, p_firma_menor text, p_contenido jsonb, p_ua text)
returns timestamptz language plpgsql security definer set search_path = public as $$
declare v_fecha timestamptz := now();
begin
  if p_firma is null or length(p_firma) < 200 then raise exception 'Falta la firma'; end if;
  if length(p_firma) > 400000 or length(coalesce(p_firma_menor, '')) > 400000 then raise exception 'La firma es demasiado grande'; end if;
  update public.contratos
     set estado = 'firmado', datos = p_datos, firma = p_firma, firma_menor = p_firma_menor,
         contenido = p_contenido, firmado_at = v_fecha, firmado_ua = left(p_ua, 300)
   where id = p_id and user_id = auth.uid() and estado = 'pendiente';
  if not found then raise exception 'Este contrato no está pendiente de firma'; end if;
  return v_fecha;
end $$;
revoke all on function public.firmar_contrato(bigint, jsonb, text, text, jsonb, text) from public, anon;
grant execute on function public.firmar_contrato(bigint, jsonb, text, text, jsonb, text) to authenticated;

do $$ begin
  alter publication supabase_realtime add table public.contratos;
exception when duplicate_object then null; end $$;
