-- Iberail · «Iberail Protect» (seguro de viaje que se ofrece en «Mis grupos»)
-- Ejecutar UNA vez en Supabase → SQL Editor.
--
-- Se puede ejecutar varias veces (también si ya ejecutaste una versión anterior).
-- El equipo activa la oferta en cada grupo (precio, tipo de cobertura, fecha límite).
-- El viajero pulsa «Contratar y pagar»: paga el seguro APARTE del viaje en Stripe (stripe-checkout con seguro:true)
-- y el webhook lo apunta aquí como «pagado». El equipo lo contrata y lo marca «contratado» con el nº de póliza.
-- El seguro NO toca grupo_miembros.importe ni la tabla pagos.

create table if not exists public.seguro_ofertas (
  grupo_id    bigint primary key references public.grupos(id) on delete cascade,
  activo      boolean not null default true,
  plan        text not null default 'completo' check (plan in ('completo', 'basico')),
  cancelacion boolean not null default true,
  precio      numeric(10,2) not null check (precio > 0),
  limite      date,
  aseguradora text,
  updated_at  timestamptz not null default now()
);

create table if not exists public.seguros (
  id          bigint generated by default as identity primary key,
  grupo_id    bigint not null references public.grupos(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  precio      numeric(10,2) not null,
  plan        text not null,
  cancelacion boolean not null,
  estado      text not null default 'pagado',
  poliza      text,
  created_at  timestamptz not null default now(),
  contratado_at timestamptz
);
alter table public.seguros add column if not exists stripe_session text;
alter table public.seguros add column if not exists pagado_at timestamptz;
alter table public.seguros drop constraint if exists seguros_estado_check;
alter table public.seguros add constraint seguros_estado_check check (estado in ('solicitado', 'pagado', 'contratado', 'anulado'));
create unique index if not exists seguros_stripe_idx on public.seguros (stripe_session) where stripe_session is not null;
create unique index if not exists seguros_vigente_idx on public.seguros (grupo_id, user_id) where estado <> 'anulado';

alter table public.seguro_ofertas enable row level security;
drop policy if exists "seguro_ofertas: ver mi grupo" on public.seguro_ofertas;
create policy "seguro_ofertas: ver mi grupo" on public.seguro_ofertas for select to authenticated
  using (public.is_admin() or exists (select 1 from public.grupo_miembros m where m.grupo_id = seguro_ofertas.grupo_id and m.user_id = auth.uid()));
drop policy if exists "seguro_ofertas: equipo" on public.seguro_ofertas;
create policy "seguro_ofertas: equipo" on public.seguro_ofertas for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

alter table public.seguros enable row level security;
drop policy if exists "seguros: ver el mío" on public.seguros;
create policy "seguros: ver el mío" on public.seguros for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
drop policy if exists "seguros: equipo" on public.seguros;
create policy "seguros: equipo" on public.seguros for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- versión anterior: el seguro ya no se suma al viaje
drop function if exists public.pedir_seguro(bigint);

-- el equipo lo anula (la devolución, si la hay, se hace desde Stripe)
create or replace function public.anular_seguro(p_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Solo el equipo'; end if;
  update seguros set estado = 'anulado' where id = p_id;
end $$;
revoke all on function public.anular_seguro(bigint) from public, anon;
grant execute on function public.anular_seguro(bigint) to authenticated;

do $$ begin
  alter publication supabase_realtime add table public.seguros;
exception when duplicate_object then null; end $$;
